version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  labels:
    - "3. to review"
    - "dependencies"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
    - "3. to review"
    - "dependencies"

# Main stableXX npm
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable25
  labels:
    - "3. to review"
    - "dependencies"
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
