OC.L10N.register(
    "bruteforcesettings",
    {
    "Brute-force settings" : "إعدادات كاشف هجمات القوة الكاسحة Brute-force",
    "Whitelist IPs" : "القائمة البيضاء لعناوين IP",
    "Brute-force protection is meant to protect Nextcloud servers from attempts to\nguess account passwords in various ways. Besides the obvious \"*let's try a big\nlist of commonly used passwords*\" attack, it also makes it harder to use\nslightly more sophisticated attacks via the reset password form or trying to\nfind app password tokens.\n\nIf triggered, brute-force protection makes requests coming from an IP on a\nbrute-force protected controller with the same API slower for a 24 hour period.\n\nWith this app, the admin can exempt an IP address or range from this\nprotection which can be useful for testing purposes or when there are false\npositives due to a lot of accounts on one IP address." : "تهدف \"مكافحة هجمات القوة الكاسحة\" brute-force protection إلى حماية خوادم نكست كلاود من محاولات تخمين كلمات مرور الحسابات و ذلك بتكرار الاحتمالات المتعددة للكلمة. وكذلك الطريقة الشائعة \"*لنجرب قائمة من كلمات المرور شائعة الاستخدام*\"، كما أنه يزيد من صعوبة هجمات أخرى أكثر تعقيدًا عبر نموذج محاولة إعادة تعيين كلمة المرور، أو محاولة إيجاد أَمَارَة token التطبيق. عند تشغيلها، فإن\"مكافحة هجمات القوة الكاسحة\" تقوم بتبطئة الطلبات القادمة من عنوان IP المشتبه به على نفس واجهة الـ API لمدة 24 ساعة. باستخدام هذا التطبيق، يمكن للمشرف استثناء عنوان IP ما أو نطاقٍ من العناوين من هذا الحماية؛ الأمر الذي قد يكون مفيداً في حالات الاختبار أو عندما تكون هناك إنذارات كاذبة بسبب وجود الكثير من الحسابات الشرعية على عنوان IP واحد.",
    "Brute-force IP whitelist" : "القائمة البيضاء لعناوين IP للقوة الكاسحة Brute-force",
    "To whitelist IP ranges from the brute-force protection specify them below. Note that any whitelisted IP can perform authentication attempts without any throttling. For security reasons, it is recommended to whitelist as few hosts as possible or ideally even none at all." : "لإدراج نطاقات IP في القائمة البيضاء للحماية من هجمات القوة الكاسحة. حددها أدناه. لاحظ أن أي عنوان IP مدرج في القائمة البيضاء مسموحٌ له بمحاولة المصادقة دون أي تقييد. لأسباب أمنية، يُوصى بإدراج أقل عددٍ ممكنٍ من المضيفين في القائمة البيضاء، أو لا شيء على الإطلاق من الناحية المثالية.",
    "Add a new whitelist" : "إضِف قائمة بيضاء جديدة",
    "Add" : "إضافة",
    "Your remote address was identified as \"{remoteAddress}\" and is throttled at the moment by {delay}ms." : "تم تحديد عنوانك القَصِيّ على أنه \"{remoteAddress}\" و يتم التحكم فيه حاليًا بمقدار {delay} مللي ثانية.",
    "Your remote address was identified as \"{remoteAddress}\" and is bypassing brute-force protection." : "تمّ التعرُّف على عنونك البعيد كـ \"{remoteAddress}\" و قد تمّ تمكينه من تخطِّي حاجز \"مكافحة هجمات القوة الكاسحة\".",
    "Your remote address was identified as \"{remoteAddress}\" and is not actively throttled at the moment." : "تم تحديد عنوانك القَصِيّ على أنه \"{remoteAddress}\" و لا يتم التحكم فيه بشكل نشط في الوقت الحالي.",
    "There was an error adding the IP to the whitelist." : "حدث خطأ أثناء إضافة عنوان الـ IP إلى القائمة البيضاء",
    "Delete entry for {subnet}" : "حذف مدخل لـ {subnet}.",
    "Brute Force Protection is meant to protect Nextcloud servers from attempts to\nguess account passwords in various ways. Besides the obvious \"*let's try a big\nlist of commonly used passwords*\" attack, it also makes it harder to use\nslightly more sophisticated attacks via the reset password form or trying to\nfind app password tokens.\n\nIf triggered, brute force protection makes requests coming from an IP on a\nbruteforce protected controller with the same API slower for a 24 hour period.\n\nWith this app, the admin can exempt an IP address or range from this\nprotection which can be useful for testing purposes or when there are false\npositives due to a lot of accounts on one IP address." : "تهدف الحماية من هجمات القوة الكاسحة إلى حماية خوادم نكست كلاود من محاولات تخمين كلمات مرور الحساب بطرق مختلفة. إلى جانب الهجوم الواضح \"* لنجرب قائمة كبيرة من كلمات المرور الشائعة الاستخدام *\" ، فإنه يجعل أيضًا من الصعب استخدام \"هجمات أكثر تعقيدًا قليلاً عبر نموذج إعادة تعيين كلمة المرور أو محاولة البحث عن الرموز المميزة لكلمات مرور التطبيق\". \n\nتجعل الحماية من القوة الغاشمة الطلبات الواردة من عنوان IP على وحدة تحكم محمية بقوة bruteforce مع نفس واجهة برمجة التطبيقات أبطأ لمدة 24 ساعة. \n\nمع هذا التطبيق، يمكن للمسؤول استثناء عنوان IP أو النطاق من هذه الحماية التي يمكن أن تكون مفيدة لأغراض الاختبار أو عندما تكون هناك مواضع خاطئة بسبب وجود الكثير من الحسابات على عنوان IP واحدٍ.",
    "Add new whitelist" : "إضافة إلى القائمة البيضاء",
    "Delete" : "حذف "
},
"nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;");
