OC.L10N.register(
    "bruteforcesettings",
    {
    "Brute-force settings" : "Configuraciones para ataques de fuerza bruta",
    "Whitelist IPs" : "Lista blanca de IPs",
    "Brute Force Protection is meant to protect Nextcloud servers from attempts to\nguess user passwords in various ways. Besides the obvious \"*let's try a big\nlist of commonly used passwords*\" attack, it also makes it harder to use\nslightly more sophisticated attacks via the reset password form or trying to\nfind app password tokens.\n\nIf triggered, brute force protection makes requests coming from an IP on a\nbruteforce protected controller with the same API slower for a 24 hour period.\n\nWith this app, the admin can exempt an IP address or range from this\nprotection which can be useful for testing purposes or when there are false\npositives due to a lot of users on one IP address." : "La protección contra fuerza bruta está diseñada para proteger a los servidores NextCloud de intentos de\nobtener las contraseñas de usuario de varias maneras. Además del obvio ataque \"*vamos a probar una gran\n lista de contraseñas frecuentes*\", también dificulta el uso de ataques más sofisticados como los que son vía el formulario de reseteo de la contraseña o probando a\nencontrar los tokens de contraseña de la aplicación.\n\nSi se activa, la protección hace que las solicitudes que provengan de esa IP se redirijan\na un controlador protegido contra fuerza bruta con la misma API pero ralentizada durante un periodo de 24 horas.\n\nCon esta app, el administrador puede eximir una IP o un rango de ellas de esta\nprotección, puede ser útil para fines de prueba o cuando hay falsos\npositivos debido a una gran cantidad de usuarios en una dirección IP.",
    "Brute-force IP whitelist" : "Lista blanca de IP para ataques de fuerza bruta"
},
"nplurals=2; plural=(n != 1);");
